core/main/model/objects/Sentry_Event__e/Sentry_Event__e.object-meta.xml
<CustomObject>
    <label>Sentry Event</label>
    <pluralLabel>Sentry Events</pluralLabel>
</CustomObject>

sentry-core/core/main/model/objects/Sentry_Payload__c/Sentry_Payload__c.object-meta.xml
<CustomObject>
    <label>Sentry Payload</label>
    <nameField>
        <label>Event Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sentry Payloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

core/main/model/objects/Sentry_Payload__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sentry-core/core/main/model/objects/Sentry_Payload__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sentry-core/core/main/model/objects/Sentry_Payload__c/fields/Stored_By_Sentry__c.field-meta.xml
<CustomField>
    <fullName>Stored_By_Sentry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stored By Sentry</label>
    <type>Checkbox</type>
</CustomField>

core/main/sdk/classes/SentryTransport.cls
public with sharing class SentryTransport {
  private static Http http = new Http();
  private static SentryConfigInterface config = SentryConfigFactory.getConfig();

  public static void proccess(List<Sentry_Event__e> pes) {
    List<SentryEvent> events = parsePlatformEvents(pes);

    // TODO Call before send events processors
    /*
# Things that will be populated by transport
* Environement : Type of org
* sdk : info about sentry sdk
* server_name : Org Id
* timestamp: from platform event crated date
*/

    // save the payloads
    Set<Id> payloadIds = savePayloads(events);
    send(payloadIds);
  }

  private static List<SentryEvent> parsePlatformEvents(
    List<Sentry_Event__e> pes
  ) {
    List<SentryEvent> events = new List<SentryEvent>();

    for (Sentry_Event__e pe : pes) {
      events.add(new SentryEvent(pe));
    }

    return events;
  }

  private static Set<Id> savePayloads(List<SentryEvent> events) {
    List<Sentry_Payload__c> payloads = new List<Sentry_Payload__c>();
    for (SentryEvent event : events) {
      Sentry_Payload__c payload = new Sentry_Payload__c();
      payload.Name = event.eventId;
      payload.Payload__c = event.toJsonPayload();
      payloads.add(payload);
    }
    insert payloads;
    return (new Map<Id, Sentry_Payload__c>(payloads)).keySet();
  }

  @Future(Callout=true)
  private static void send(Set<id> payloadIds) {
    List<Sentry_Payload__c> payloads = [
      SELECT Id, name, Payload__c
      FROM Sentry_Payload__c
      WHERE id IN :payloadIds
    ];
    for (Sentry_Payload__c payload : payloads) {
      try {
        HttpResponse response = http.send(getStoreRequest(payload.Payload__c));
        if (response.getStatusCode() != 200) {
          throw new CalloutException(
            'Sentry rejected the event [' +
              response.getStatusCode() +
              ']: ' +
              response.getBody()
          );
        }
        payload.Stored_By_Sentry__c = true;
      } catch (Exception e) {
        payload.Error__c = e.getMessage();
      }
    }
    update payloads;
  }

  private static HttpRequest getStoreRequest(String payload) {
    HttpRequest request = new HttpRequest();
    request.setEndpoint(config.getDSN().storeEndpoint.toExternalForm());
    request.setMethod('POST');
    request.setHeader('Content-Type', 'application/json');
    request.setHeader('User-Agent', SentryClientSDKInfo.getFullName());
    request.setHeader(
      'X-Sentry-Auth',
      'Sentry ' +
      String.join(
        new List<String>{
          'sentry_version=7', // Sentry api version
          'sentry_key=' + config.getDSN().publicKey,
          'sentry_client=' + SentryClientSDKInfo.getFullName()
        },
        ', '
      )
    );
    request.setBody(payload);

    return request;
  }
}